version: '2'

services:
  drone-server:
    image: drone/drone:0.8
    ports:
      - 80:8000
      - 9000:9000
    volumes:
      - /var/lib/drone:/var/lib/drone
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_ORGS=lampepfl
      - DRONE_ADMIN=felixmulder,smarter,DarkDimius,NicolasStucki,odersky,liufengyun,OlivierBlanvillain,allanrenucci,gsps,Duhemm
      - DRONE_HOST=http://dotty-ci.epfl.ch
      - DRONE_GITHUB=true
      - DRONE_GITHUB_MERGE_REF=false
      - DRONE_GITHUB_CLIENT=<client here>
      - DRONE_GITHUB_SECRET=<secret here>
      - DRONE_SECRET=<server/agent secret here>

  drone-agent:
    image: drone/agent:0.8
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_TIMEOUT=10m
      - DRONE_MAX_PROCS=3
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=<server/agent secret here>
